#!/usr/bin/env -S bash

set -e
set -o pipefail

cd "$(dirname "$0")"

(
while read -r link; do
    wget --tries=0 --continue --no-directories --trust-server-names "$link"
done
) << EOT
https://www.openslr.org/resources/30/si_lk.tar.gz
https://www.openslr.org/resources/30/si_lk.lines.txt
https://www.openslr.org/resources/32/af_za.tar.gz
https://www.openslr.org/resources/32/st_za.tar.gz
https://www.openslr.org/resources/32/tn_za.tar.gz
https://www.openslr.org/resources/32/xh_za.tar.gz
https://www.openslr.org/resources/35/asr_javanese_0.zip
https://www.openslr.org/resources/35/asr_javanese_1.zip
https://www.openslr.org/resources/35/asr_javanese_2.zip
https://www.openslr.org/resources/35/asr_javanese_3.zip
https://www.openslr.org/resources/35/asr_javanese_4.zip
https://www.openslr.org/resources/35/asr_javanese_5.zip
https://www.openslr.org/resources/35/asr_javanese_6.zip
https://www.openslr.org/resources/35/asr_javanese_7.zip
https://www.openslr.org/resources/35/asr_javanese_8.zip
https://www.openslr.org/resources/35/asr_javanese_9.zip
https://www.openslr.org/resources/35/asr_javanese_a.zip
https://www.openslr.org/resources/35/asr_javanese_b.zip
https://www.openslr.org/resources/35/asr_javanese_c.zip
https://www.openslr.org/resources/35/asr_javanese_e.zip
https://www.openslr.org/resources/35/asr_javanese_f.zip
https://www.openslr.org/resources/36/asr_sundanese_0.zip
https://www.openslr.org/resources/36/asr_sundanese_1.zip
https://www.openslr.org/resources/36/asr_sundanese_2.zip
https://www.openslr.org/resources/36/asr_sundanese_3.zip
https://www.openslr.org/resources/36/asr_sundanese_4.zip
https://www.openslr.org/resources/36/asr_sundanese_5.zip
https://www.openslr.org/resources/36/asr_sundanese_6.zip
https://www.openslr.org/resources/36/asr_sundanese_7.zip
https://www.openslr.org/resources/36/asr_sundanese_8.zip
https://www.openslr.org/resources/36/asr_sundanese_9.zip
https://www.openslr.org/resources/36/asr_sundanese_a.zip
https://www.openslr.org/resources/36/asr_sundanese_b.zip
https://www.openslr.org/resources/36/asr_sundanese_c.zip
https://www.openslr.org/resources/36/asr_sundanese_d.zip
https://www.openslr.org/resources/36/asr_sundanese_e.zip
https://www.openslr.org/resources/36/asr_sundanese_f.zip
https://www.openslr.org/resources/37/bn_bd.zip
https://www.openslr.org/resources/37/bn_in.zip
https://www.openslr.org/resources/41/jv_id_female.zip
https://www.openslr.org/resources/41/jv_id_male.zip
https://www.openslr.org/resources/42/km_kh_male.zip
https://www.openslr.org/resources/43/ne_np_female.zip
https://www.openslr.org/resources/44/su_id_female.zip
https://www.openslr.org/resources/44/su_id_male.zip
https://www.openslr.org/resources/52/asr_sinhala_0.zip
https://www.openslr.org/resources/52/asr_sinhala_1.zip
https://www.openslr.org/resources/52/asr_sinhala_2.zip
https://www.openslr.org/resources/52/asr_sinhala_3.zip
https://www.openslr.org/resources/52/asr_sinhala_4.zip
https://www.openslr.org/resources/52/asr_sinhala_5.zip
https://www.openslr.org/resources/52/asr_sinhala_6.zip
https://www.openslr.org/resources/52/asr_sinhala_7.zip
https://www.openslr.org/resources/52/asr_sinhala_8.zip
https://www.openslr.org/resources/52/asr_sinhala_9.zip
https://www.openslr.org/resources/52/asr_sinhala_a.zip
https://www.openslr.org/resources/52/asr_sinhala_b.zip
https://www.openslr.org/resources/52/asr_sinhala_c.zip
https://www.openslr.org/resources/52/asr_sinhala_d.zip
https://www.openslr.org/resources/52/asr_sinhala_e.zip
https://www.openslr.org/resources/52/asr_sinhala_f.zip
https://www.openslr.org/resources/53/asr_bengali_0.zip
https://www.openslr.org/resources/53/asr_bengali_1.zip
https://www.openslr.org/resources/53/asr_bengali_2.zip
https://www.openslr.org/resources/53/asr_bengali_3.zip
https://www.openslr.org/resources/53/asr_bengali_4.zip
https://www.openslr.org/resources/53/asr_bengali_5.zip
https://www.openslr.org/resources/53/asr_bengali_6.zip
https://www.openslr.org/resources/53/asr_bengali_7.zip
https://www.openslr.org/resources/53/asr_bengali_8.zip
https://www.openslr.org/resources/53/asr_bengali_9.zip
https://www.openslr.org/resources/53/asr_bengali_a.zip
https://www.openslr.org/resources/53/asr_bengali_b.zip
https://www.openslr.org/resources/53/asr_bengali_c.zip
https://www.openslr.org/resources/53/asr_bengali_d.zip
https://www.openslr.org/resources/53/asr_bengali_e.zip
https://www.openslr.org/resources/53/asr_bengali_f.zip
https://www.openslr.org/resources/54/asr_nepali_0.zip
https://www.openslr.org/resources/54/asr_nepali_1.zip
https://www.openslr.org/resources/54/asr_nepali_2.zip
https://www.openslr.org/resources/54/asr_nepali_3.zip
https://www.openslr.org/resources/54/asr_nepali_4.zip
https://www.openslr.org/resources/54/asr_nepali_5.zip
https://www.openslr.org/resources/54/asr_nepali_6.zip
https://www.openslr.org/resources/54/asr_nepali_7.zip
https://www.openslr.org/resources/54/asr_nepali_8.zip
https://www.openslr.org/resources/54/asr_nepali_9.zip
https://www.openslr.org/resources/54/asr_nepali_a.zip
https://www.openslr.org/resources/54/asr_nepali_b.zip
https://www.openslr.org/resources/54/asr_nepali_c.zip
https://www.openslr.org/resources/54/asr_nepali_d.zip
https://www.openslr.org/resources/54/asr_nepali_e.zip
https://www.openslr.org/resources/54/asr_nepali_f.zip
https://www.openslr.org/resources/61/es_ar_female.zip
https://www.openslr.org/resources/61/es_ar_male.zip
https://www.openslr.org/resources/61/es_weather_messages.zip
https://www.openslr.org/resources/63/ml_in_female.zip
https://www.openslr.org/resources/63/ml_in_male.zip
https://www.openslr.org/resources/64/mr_in_female.zip
https://www.openslr.org/resources/65/ta_in_female.zip
https://www.openslr.org/resources/65/ta_in_male.zip
https://www.openslr.org/resources/66/te_in_female.zip
https://www.openslr.org/resources/66/te_in_male.zip
https://www.openslr.org/resources/69/ca_es_female.zip
https://www.openslr.org/resources/69/ca_es_male.zip
https://www.openslr.org/resources/70/en_ng_female.zip
https://www.openslr.org/resources/70/en_ng_male.zip
https://www.openslr.org/resources/71/es_cl_female.zip
https://www.openslr.org/resources/71/es_cl_male.zip
https://www.openslr.org/resources/72/es_co_female.zip
https://www.openslr.org/resources/72/es_co_male.zip
https://www.openslr.org/resources/73/es_pe_female.zip
https://www.openslr.org/resources/73/es_pe_male.zip
https://www.openslr.org/resources/74/es_pr_female.zip
https://www.openslr.org/resources/75/es_ve_female.zip
https://www.openslr.org/resources/75/es_ve_male.zip
https://www.openslr.org/resources/76/eu_es_female.zip
https://www.openslr.org/resources/76/eu_es_male.zip
https://www.openslr.org/resources/77/gl_es_female.zip
https://www.openslr.org/resources/77/gl_es_male.zip
https://www.openslr.org/resources/78/gu_in_female.zip
https://www.openslr.org/resources/78/gu_in_male.zip
https://www.openslr.org/resources/79/kn_in_female.zip
https://www.openslr.org/resources/79/kn_in_male.zip
https://www.openslr.org/resources/80/my_mm_female.zip
https://www.openslr.org/resources/83/irish_english_male.zip
https://www.openslr.org/resources/83/midlands_english_female.zip
https://www.openslr.org/resources/83/midlands_english_male.zip
https://www.openslr.org/resources/83/northern_english_female.zip
https://www.openslr.org/resources/83/northern_english_male.zip
https://www.openslr.org/resources/83/scottish_english_female.zip
https://www.openslr.org/resources/83/scottish_english_male.zip
https://www.openslr.org/resources/83/southern_english_female.zip
https://www.openslr.org/resources/83/southern_english_male.zip
https://www.openslr.org/resources/83/welsh_english_female.zip
https://www.openslr.org/resources/83/welsh_english_male.zip
https://www.openslr.org/resources/86/yo_ng_female.zip
https://www.openslr.org/resources/86/yo_ng_male.zip
EOT